import { SelectProps } from 'ant-design-vue';
import {
  ListInterface,
  PageInterface,
  partPartial,
} from '../../../interface/index';
import { SkuSingleInterface } from '../../../api/interface';

export interface OrderListRequestParamsInterface {
  order_search_key: string;
  order_search_value: string;
  good_search_key: string;
  good_search_value: string;
  pay_status_arr: number[];
  deliver_arr: number[];
  shop_name: string;
  supplier_id: number;
  user_level: number;
  category_id: number;
  category_id_array: number[];
  brand_name_arr: number[];
  user_id: number;
  create_mode_arr: number[];
  app_platform: string;
  sale_mode: number;
  delivery_mode: number;
  pay_type: number;
  payment_type: number;
  is_invoice: number;
  is_support_local: number;
  goods_source: number;
  distribute_order: number;
  owner_site_id: number;
  createTime: [string, string];
  create_time_start: string;
  create_time_end: string;
  create_user_id: number;
  paymentTime: [string, string];
  pay_time_start: string;
  pay_time_end: string;
  pre_delivery_start_date: string;
  pre_delivery_end_date: string;
  sub_status_arr: string[];
  trade_no: number;
  deliveryTime: [string, string];
  recommend_staff: string;
  marketing_type: number;
  order_type: number;
  is_return: number;
  package_no: string;
  is_mem_msg: number;
  sub_org_id: number;
  gas_account: string;
  business_id: number;
  is_pre_subscribe: number;
  source_site_id: number;
  spell_order_status: number;
  is_out_supplier: number;
  address: number[];
  pay_mode: number;
}

export type OrderListRequestResultInterface =
  ListInterface<OrderListRequestResultItemInterface> & {
    total0: number;
    total5: number;
    total20: number;
    total30: number;
    total40: number;
    total50: number;
    total60: number;
    total110: number;
    totalAll: number;
    total: number;
    page: number;
    page_size: number;
  };

export type OrderLsitParamsPageInterface =
  Partial<OrderListRequestParamsInterface> & PageInterface;

export interface OrderListRequestResultItemInterface {
  activeKey: string;
  pay_mode: {
    value: number;
    name: string;
  };
  spell_order_status: number;
  receipt: number;
  sub_status_name: string;
  status: number;
  ono: string;
  approval_status: number;
  process_seq: string;
  approval_status_name: string;
  approval_time: number;
  osl_seq: string;
  id: number;
  enterprise_id: number;
  out_ono: string;
  user_id: number;
  user_id_string: string;
  user_level: string;
  tel: string;
  goods_source: number;
  goods_source_name: string;
  pay_mode_name: string;
  create_user_id: number;
  user_name: string;
  user_mobile: string;
  name: string;
  mobile: string;
  province_id: number;
  city_id: number;
  district_id: number;
  street_id: number;
  address: string;
  province_name: string;
  city_name: string;
  district_name: string;
  street_name: string;
  detailAddress: string;
  zipcode: string;
  gas_account: string;
  buy_company_name: string;
  apply_delivery_time: string;
  order_type: {
    value: number;
    name: string;
  };
  order_type_name: string;
  marketing_type: {
    value: string;
    name: string;
  };
  marketing_type_name: string;
  group_status: string;
  is_credit_order: number;
  create_time: string;
  create_datetime: string;
  order_time: string;
  order_datetime: string;
  confirm_time: string;
  pay_time: string;
  pay_datetime: string;
  pay_status: number;
  pre_delivery_time: string;
  delivery_time: string;
  delivery_datetime: string;
  recommend_staff: string;
  sub_status: {
    value: number;
    name: string;
  };
  sub_org_id: number;
  sub_org_enterprise_id: number;
  sub_org_name: string;
  distribute_org_id: number;
  distribute_org_enterprise_id: number;
  distribute_org_name: string;
  sale_mode: {
    value: number;
    name: string;
  };
  sale_mode_name: string;
  owner_site_id: number;
  shop_name: string;
  store_code: string;
  shop_id: number;
  business_id: number;
  business_name: string;
  supplier_id: number;
  supplier_name: string;
  delivery_mode: {
    value: number;
    name: string;
  };
  create_mode: {
    value: number;
    name: string;
  };
  create_mode_name: string;
  mem_msg: string;
  merchant_remark: string;
  is_invoice: number;
  is_invoice_print: number;
  is_return: number;
  is_returning: number;
  pay_type: {
    value: number;
    name: string;
  };
  pay_type_name: string;
  app_platform: string;
  trade_no: string;
  external_system_code: string;
  delivery_channel: number;
  is_delivery: number;
  sub_purchase_amount: number;
  sub_extra_fee: number;
  sub_total_amount: number | string;
  sub_total_pay: number;
  sub_total_freight: string;
  sub_total_price: number;
  sub_part_discount: number;
  sub_credit: string;
  sub_card_ticket_fee: string;
  sub_freight: number;
  sub_freight_use_credit: number;
  sub_use_gift_card_fee: number;
  sub_freight_card_ticket_fee: number;
  is_supplier_calculated: number;
  supplier_invoice_status: number;
  supplier_invoice_number: string;
  supplier_invoice_type: number;
  out_delivery_tag: number;
  distribute_order: number;
  distribute_order_name: string;
  is_support_local: number;
  is_support_local_name: string;
  shop_account_id: number;
  salesman_node_id: number;
  salesman_node_name: string;
  stock_node_name: string;
  stock_node_id: number;
  return_amount: number;
  is_pre_subscribe: number;
  is_pre_subscribe_name: string;
  service_no: string;
  sale_method: number;
  sale_type: number;
  sale_channel: number;
  stock_sale_delivery: number;
  sale_method_name: string;
  sale_type_name: string;
  sale_channel_name: string;
  stock_sale_delivery_name: string;
  is_allow_create_outstock: boolean;
  cost_price: number;
  shop_retail_price: number;
  allow_invoice_amount: number;
  item: {
    oi_seq: string;
    use_credit_amount: number;
    pic_url: string;
    pic_url_pic: string;
    goods_name: string;
    sale_unit: string;
    sku_id: number;
    cost_price: number;
    sku_code: string;
    shop_goods_code: string;
    shop_goods_id: number;
    sn: string;
    area_code: string;
    purchase_category_id: number;
    purchase_category_name: string;
    tms_material_code: string;
    snapshot: number;
    sku_spec: {
      spec_id: number;
      spec_name: string;
      spec_value: string;
      spec_group_id: number;
      spec_value_id: number;
      spec_group_name: string;
    }[];
    brand_name: string;
    category_id: string;
    category_name: string;
    first_category_name: string;
    second_category_name: string;
    third_category_name: string;
    price: number | string;
    real_price: number | string;
    purchase_amount: number;
    oi_use_gift_card_fee: number;
    freight: number;
    oiv_seq: string;
    oim_seq: string;
    qty: number;
    every_real_price: string;
    invoice_qty: number;
    invoice_item_amount: string;
    output_untax_total_amount: string;
    spbm: string;
    delivery_qty: number;
    buy_amount: number;
    item_extra_fee: number;
    item_part_discount_extra_fee: number;
    item_marketing_discount_extra_fee: number;
    output_tax_rate: number;
    output_tax_total_amount: string;
    input_tax_rate: number;
    shop_retail_price: number;
    sku_specs: string;
    goods_pics: string;
  }[];
  express: [];
  tms_customer: string;
  create_user_name: string;
  shop_account_name: string;
  user: {
    username: string;
    user_id: number;
    user_level: string;
    user_level_name: string;
  };
  consignee: {
    name: string;
    mobile: string;
    city_id: number;
    district_id: number;
    street_id: number;
    address: string;
    zipcode: string;
  };
  is_electron: number;
  business_user: number;
  owner_site_name: string;
  owner_org_name: string;
  verify_status: {
    value: number;
    name: string;
  };
  grouping: string;
  cancel_time: string;
  pay_deadline: string;
  group_time: string;
}

export interface ConfirmsignRequestParamsInterface {
  user_id: string;
  osl_seq: string;
  operator: string;
}

export type AddParamsInterface = Partial<{
  qty: number;
  total_price: number;
  freight: number;
  entryMode: string;
  sale_mode: string;
  buyer_note: string;
  api_type: number;
  out_ono: string;
  businessType: string;
  pay_mode_name: string;
  phone: string;
  wx_nickname: string;
  user_level_name: string;
  username: string;
  name: string;
  company_name: string;
  stockFreeze: string;
  delivery_mode: number;
  isInvoice: number;
  pay_mode: number;
  user_id: string;
  site_id: number;
  merchant_note: string;
  note: string;
  delivery_mode_list: [];
  buyer_shop_goods_list: {
    qty: number;
    shop_goods_id: number;
    adjust_mount: number;
  }[];
}> & {
  order_invoice: Partial<{
    invoice_form: number;
    invoice_kind: number;
    content_type: number;
    invoice_notice: string;
    invoice_type: number;
    invoice_title: string;
    vat_number: string;
    et_address: string;
    et_phone_num: string;
    et_bank_name: string;
    et_bank_account: string;
    invoice_username: string;
    invoice_phone_num: string;
    invoice_email: string;
    province_id: number;
    province_name: string;
    city_id: number;
    city_name: string;
    district_id: number;
    district_name: string;
    street_id: number;
    street_name: string;
    invoice_address: string;
    apply_scene: number;
  }> & {
    mArea: number[];
  };
  shop_goods_list: {
    qty: number;
    shop_goods_id: number;
    adjust_mount: number;
  }[];
  validator: { total_pay?: number };
  addressInfo: Partial<{
    name: string;
    mobile: string;
    tel: string;
    email: string;
    province_id: number;
    province_name: string;
    city_id: number;
    city_name: string;
    district_id: number;
    district_name: string;
    street_id: number;
    street_name: string;
    real_name: string;
    zipcode: string;
    address: string;
  }> & { addressIds: number[] };
};

export type InvoiceRepairInvoiceRequestParamsInterface = Partial<{
  invoice_type: number;
  invoice_kind: number;
  invoice_title: string;
  vat_number: string;
  et_bank_name: string;
  et_bank_account: string;
  et_address: string;
  et_phone_num: string;
  invoice_username: string;
  invoice_phone_num: string;
  invoice_email: string;
  invoice_address: string;
  mArea: number[];
  name: string;
  sale_tax_num: string;
  sale_address: string;
  sale_phone: string;
  sale_bank: string;
  sale_account: string;
}>;

export interface InvoiceCodeSingleInterface {
  invoice_company_code: string;
  invoice_channel: string;
  sale_tax_num: string;
  sale_company: string;
  sale_account: string;
  sale_bank: string;
  sale_address: string;
  sale_phone: string;
  payee: string;
  checker: string;
  clerk: string;
  remark: string;
}
export type OrderDetailResultInterface = Partial<{
  id: number;
  user_id: number;
  customer_id: number;
  lock_stock: number;
  from_userid: number;
  extension_userid: number;
  group_endtime: number;
  group_snapshoot: string;
  share_userid: number;
  node_id: number;
  recommend_staff: string;
  ono: string;
  ono_sn: number;
  osl_seq: string;
  type: number;
  sale_mode: number;
  settlement_method: number;
  sale_guests: number;
  order_transfer_time: number;
  order_trans_reason: string;
  delivery_mode: number;
  express_company_no: string;
  adjust_amount: number;
  sub_total_price: number;
  sub_total_pay: number;
  productamt: number;
  status: number;
  stock_status: number;
  group_id: string;
  group_time: number;
  confirm_time: number;
  cancel_time: number;
  cancel_reason: string;
  shop_id: number;
  shop_name: string;
  supplier_id: number;
  supplier_code: string;
  store_code: string;
  merchant_remark: string;
  mem_msg: string;
  delivery_remark: string;
  use_credit_amount: number;
  is_invoice_name:string
  create_time_string:string;
  is_return_name:string;
  confirm_time_string:string;
  use_credit: number;
  freight: number;
  freight_discount: number;
  freight_use_credit: number;
  is_support_local_name:string;
  pay_time_string:string;
  part_discount: number;
  source_org_name:string;
  pre_delivery_time_string:string;
  delivery_time_string:string
  marketing_discount: number;
  level_discount: number;
  use_level_discount: number;
  pay_time: number;
  traded_close_time: number;
  pre_delivery_time: number;
  delivery_time: number;
  sign_time: number;
  app_platform: string;
  create_mode: number;
  user_level: number;
  user_kind: string;
  oc_seq: string;
  verify_exception_time: number;
  verify_exception_remark: string;
  verify_status: number;
  verify_time: number;
  verify_usr: string;
  verify_remark: string;
  order_type: number;
  sa_value: string;
  sa_channel: string;
  order_sub_type: number;
  down_payment_time: number;
  down_payment: number;
  stock_sale_delivery: number;
  sale_method: number;
  sale_channel: number;
  order_flag: string;
  marketing_type: string;
  marketing_code: string;
  comment_time: number;
  split_flag: string;
  stock_check_type: number;
  order_month: number;
  order_time: number;
  item_sum: number;
  business_id: number;
  sub_org_id: number;
  stock_node_org_id: number;
  pick_up_time: number;
  jv_company_id: number;
  owner_site_id: number;
  distribute_order: number;
  distribute_org_id: number;
  buy_company_name: string;
  source_site_id: number;
  employee_site_id: number;
  use_card_ticket_fee: number;
  freight_card_ticket_fee: number;
  use_gift_card_fee: number;
  is_support_local: number;
  invoice_channel: string;
  is_delete: number;
  enterprise_id: number;
  external_system_code: string;
  goods_source: number;
  spell_order_status: number;
  tms_customer: string;
  drop_shipping: number;
  collection_payment: number;
  org_write_off: number;
  is_double_twelve_pre_sale: number;
  out_type: number;
  out_other_no: string;
  create_time: number;
  update_time: number;
  delete_time: number;
  modify_time: string;
  invoice_code: string;
  invoice_type: string;
  is_pre_subscribe: number;
  gas_account: string;
  gas_account_name: string;
  apply_delivery_time: number;
  shop_account_id: number;
  salesman_node_id: number;
  stock_node_id: number;
  third_user_id: string;
  shop_user_id: number;
  open_tcis_status: number;
  tc_msg: string;
  sale_depart_id: number;
  sub_total_buy: number;
  freight_origin: number;
  sub_total_freight: number;
  sub_total_amount: number;
  out_type_name: string;
  create_user_id: number;
  create_user_username: string;
  create_user_name: string;
  order_type_name: string;
  delivery_mode_name: string;
  status_name: string;
  create_mode_name: string;
  sale_mode_name: string;
  source_site_name: string;
  owner_site_name: string;
  business_name: string;
  user_level_name: string;
  wx_nickname: string;
  user_name: string;
  phone: string;
  shop_account_name: string;
  salesman_node_name: string;
  app_platform_name: string;
  sub_org_enterprise_id: number;
  sub_org_name: string;
  distribute_org_enterprise_id: number;
  distribute_org_name: string;
  customer_name: string;
  sale_method_name: string;
  sale_type_name: string;
  sale_channel_name: string;
  stock_sale_delivery_name: string;
  sale_guests_name: string;
  supplier_name: string;
  store_name: string;
  is_credit_order: number;
  show_cancel_btn: number;
  show_confirm_btn: number;
  process_seq: string;
  approval_status: number;
  approval_status_name: string;
  approval_time: number;
  virtual_recharge_msg: string;
  virtual_recharge_account: string;
  virtual_recharge_status: number;
  virtual_recharge_status_name: string;
  pay_type: number;
  pay_mode: number;
  trade_no: string;
  pay_deadline: number;
  out_ono: string;
  pay_type_name: string;
  qr_code_origin: string;
  wx_group: {
    c_name: string;
    chat_name: string;
  };
  pay_mode_name: string;
  item_list: any[];
  total_qty: number;
  total_adjust_amount: number;
  total_old_for_new_price: number;
  has_green_product: number;
  invoice_status: number;
  order_invoice: {};
  is_invoice: number;
  org_code: string;
  is_return: number;
  ro_seq: string;
  ro_seqs: string[];
  is_allow_create_outstock: boolean;
  operator: string;
  user_id_string: string;
  write_off_list: any[];
  show_write_off_text: number;
}>
